export type AppLanguage = "english" | "hindi" | "telugu";

export interface UserProfile {
  name: string;
  farmLocation: string;
  language: AppLanguage;
  notifications: boolean;
}

export const USER_PROFILE_KEY = "userProfile";
export const USER_PROFILE_UPDATED_EVENT = "userProfileUpdated";

export const defaultProfile: UserProfile = {
  name: "Farmer",
  farmLocation: "",
  language: "english",
  notifications: true,
};

export const getUserProfile = (): UserProfile => {
  const saved = localStorage.getItem(USER_PROFILE_KEY);
  if (!saved) return defaultProfile;

  try {
    return { ...defaultProfile, ...JSON.parse(saved) } as UserProfile;
  } catch {
    return defaultProfile;
  }
};

export const saveUserProfile = (profile: UserProfile) => {
  localStorage.setItem(USER_PROFILE_KEY, JSON.stringify(profile));
  window.dispatchEvent(new Event(USER_PROFILE_UPDATED_EVENT));
};

const translations: Record<AppLanguage, Record<string, string>> = {
  english: {
    appTitle: "AquaCare",
    appSubtitle: "Fish & Shrimp Disease Detection",
    welcomeBack: "Welcome back,",
    defaultFarmer: "Farmer",
    alerts: "Alerts",
    scanFish: "Scan Fish",
    uploadImage: "Upload Image",
    viewReports: "View Reports",
    diseaseLibrary: "Disease Library",
    recentScans: "Recent Scans",
    home: "Home",
    scan: "Scan",
    history: "History",
    profile: "Profile",
    high: "High",
    moderate: "Moderate",
    low: "Low",
    uncertain: "Uncertain",
    saveChanges: "Save Changes",
    profileTitle: "Profile",
    userInformation: "User Information",
    name: "Name",
    farmLocation: "Farm Location",
    language: "Language",
    notifications: "Notifications",
    settings: "Settings",
    helpSupport: "Help & Support",
    addLocation: "Add location",
    profileSaved: "Profile saved successfully!",
    helpComingSoon: "Help & Support coming soon!",
    englishLabel: "English",
    hindiLabel: "Hindi (हिंदी)",
    teluguLabel: "Telugu (తెలుగు)",
    selectLanguage: "Select language",
    yourName: "Your name",
    cityState: "City, State",
    scanHistory: "Scan History",
    all: "All",
    copy: "Copy",
    share: "Share",
    delete: "Delete",
    noScanHistory: "No scan history found.",
    startScanning: "Start Scanning",
    loadMore: "Load More",
    showingItems: "Showing",
    ofItems: "of",
    copyPredictionFailed: "Unable to copy this prediction.",
    shareUnavailableCopied: "Share is not available on this device. Prediction copied instead.",
    sharePredictionFailed: "Unable to share this prediction.",
    disease: "Disease",
    severity: "Severity",
    date: "Date",
    confidence: "confidence",
    aquaHealthPrediction: "Aqua Health Prediction",
    scanFishShrimp: "Scan Fish / Shrimp",
    openCamera: "Open Camera",
    chooseFromGallery: "Choose from Gallery",
    selectedImage: "Selected",
    analyzingImage: "Analyzing image…",
    testNow: "Test Now",
    scanImageError: "Error scanning image. Please try again.",
    detectionResult: "Detection Result",
    type: "Type",
    diseaseDetected: "Disease Detected",
    confidenceScore: "Confidence Score",
    advisoryInformation: "Advisory Information",
    symptoms: "Symptoms",
    causes: "Causes",
    treatment: "Treatment",
    prevention: "Prevention",
    save: "Save",
    testFurther: "Test Further",
    reportSaved: "Report saved to history!",
    diseaseDetails: "Disease Details",
    searchDiseasesSymptoms: "Search diseases or symptoms...",
    fish: "Fish",
    shrimp: "Shrimp",
    symptomsLabel: "Symptoms",
    cause: "Cause",
    noDiseasesFound: "No diseases found matching your search.",
    symptomsToRecognize: "Symptoms to Recognize",
    pageNotFound: "Oops! Page not found",
    returnHome: "Return to Home",
  },
  hindi: {
    appTitle: "एक्वाकेयर",
    appSubtitle: "मछली और झींगा रोग पहचान",
    welcomeBack: "वापसी पर स्वागत है,",
    defaultFarmer: "किसान",
    alerts: "अलर्ट",
    scanFish: "मछली स्कैन करें",
    uploadImage: "छवि अपलोड करें",
    viewReports: "रिपोर्ट देखें",
    diseaseLibrary: "रोग लाइब्रेरी",
    recentScans: "हाल की स्कैन",
    home: "होम",
    scan: "स्कैन",
    history: "इतिहास",
    profile: "प्रोफाइल",
    high: "उच्च",
    moderate: "मध्यम",
    low: "कम",
    uncertain: "अनिश्चित",
    saveChanges: "परिवर्तन सहेजें",
    profileTitle: "प्रोफाइल",
    userInformation: "उपयोगकर्ता जानकारी",
    name: "नाम",
    farmLocation: "खेत का स्थान",
    language: "भाषा",
    notifications: "सूचनाएं",
    settings: "सेटिंग्स",
    helpSupport: "मदद और समर्थन",
    addLocation: "स्थान जोड़ें",
    profileSaved: "प्रोफाइल सफलतापूर्वक सहेजा गया!",
    helpComingSoon: "मदद और समर्थन जल्द आ रहा है!",
    englishLabel: "अंग्रेज़ी",
    hindiLabel: "हिंदी",
    teluguLabel: "तेलुगु (తెలుగు)",
    selectLanguage: "भाषा चुनें",
    yourName: "आपका नाम",
    cityState: "शहर, राज्य",
    scanHistory: "स्कैन इतिहास",
    all: "सभी",
    copy: "कॉपी",
    share: "साझा करें",
    delete: "हटाएं",
    noScanHistory: "कोई स्कैन इतिहास नहीं मिला।",
    startScanning: "स्कैन शुरू करें",
    loadMore: "और लोड करें",
    showingItems: "दिखा रहे हैं",
    ofItems: "में से",
    copyPredictionFailed: "इस भविष्यवाणी को कॉपी नहीं किया जा सका।",
    shareUnavailableCopied: "इस डिवाइस में शेयर उपलब्ध नहीं है। भविष्यवाणी कॉपी कर दी गई है।",
    sharePredictionFailed: "इस भविष्यवाणी को साझा नहीं किया जा सका।",
    disease: "रोग",
    severity: "गंभीरता",
    date: "तारीख",
    confidence: "विश्वास",
    aquaHealthPrediction: "एक्वा हेल्थ भविष्यवाणी",
    scanFishShrimp: "मछली / झींगा स्कैन",
    openCamera: "कैमरा खोलें",
    chooseFromGallery: "गैलरी से चुनें",
    selectedImage: "चयनित",
    analyzingImage: "छवि का विश्लेषण हो रहा है…",
    testNow: "अभी परीक्षण करें",
    scanImageError: "छवि स्कैन करने में त्रुटि। कृपया फिर प्रयास करें।",
    detectionResult: "पहचान परिणाम",
    type: "प्रकार",
    diseaseDetected: "पहचाना गया रोग",
    confidenceScore: "विश्वास स्कोर",
    advisoryInformation: "सलाह संबंधी जानकारी",
    symptoms: "लक्षण",
    causes: "कारण",
    treatment: "उपचार",
    prevention: "रोकथाम",
    save: "सहेजें",
    testFurther: "और परीक्षण करें",
    reportSaved: "रिपोर्ट इतिहास में सहेजी गई!",
    diseaseDetails: "रोग विवरण",
    searchDiseasesSymptoms: "रोग या लक्षण खोजें...",
    fish: "मछली",
    shrimp: "झींगा",
    symptomsLabel: "लक्षण",
    cause: "कारण",
    noDiseasesFound: "आपकी खोज से मेल खाते रोग नहीं मिले।",
    symptomsToRecognize: "पहचानने योग्य लक्षण",
    pageNotFound: "ओह! पेज नहीं मिला",
    returnHome: "होम पर लौटें",
  },
  telugu: {
    appTitle: "ఆక్వాకేర్",
    appSubtitle: "చేప & రొయ్యల వ్యాధి గుర్తింపు",
    welcomeBack: "మళ్లీ స్వాగతం,",
    defaultFarmer: "రైతు",
    alerts: "అలర్ట్లు",
    scanFish: "చేప స్కాన్",
    uploadImage: "చిత్రాన్ని అప్లోడ్ చేయండి",
    viewReports: "రిపోర్టులు చూడండి",
    diseaseLibrary: "వ్యాధుల లైబ్రరీ",
    recentScans: "ఇటీవలి స్కాన్లు",
    home: "హోమ్",
    scan: "స్కాన్",
    history: "హిస్టరీ",
    profile: "ప్రొఫైల్",
    high: "అధిక",
    moderate: "మధ్యస్థ",
    low: "తక్కువ",
    uncertain: "అనిశ్చితం",
    saveChanges: "మార్పులను సేవ్ చేయండి",
    profileTitle: "ప్రొఫైల్",
    userInformation: "వినియోగదారు సమాచారం",
    name: "పేరు",
    farmLocation: "ఫారం స్థలం",
    language: "భాష",
    notifications: "నోటిఫికేషన్లు",
    settings: "సెట్టింగ్స్",
    helpSupport: "సహాయం & మద్దతు",
    addLocation: "స్థలాన్ని జోడించండి",
    profileSaved: "ప్రొఫైల్ విజయవంతంగా సేవ్ అయింది!",
    helpComingSoon: "సహాయం & మద్దతు త్వరలో వస్తుంది!",
    englishLabel: "ఇంగ్లీష్",
    hindiLabel: "హిందీ (हिंदी)",
    teluguLabel: "తెలుగు",
    selectLanguage: "భాష ఎంచుకోండి",
    yourName: "మీ పేరు",
    cityState: "నగరం, రాష్ట్రం",
    scanHistory: "స్కాన్ చరిత్ర",
    all: "అన్ని",
    copy: "కాపీ",
    share: "షేర్",
    delete: "తొలగించు",
    noScanHistory: "స్కాన్ చరిత్ర కనబడలేదు.",
    startScanning: "స్కాన్ ప్రారంభించండి",
    loadMore: "మరిన్ని లోడ్ చేయండి",
    showingItems: "చూపిస్తున్నవి",
    ofItems: "లో",
    copyPredictionFailed: "ఈ అంచనాను కాపీ చేయలేకపోయాం.",
    shareUnavailableCopied: "ఈ పరికరంలో షేర్ అందుబాటులో లేదు. అంచనాను కాపీ చేశాం.",
    sharePredictionFailed: "ఈ అంచనాను షేర్ చేయలేకపోయాం.",
    disease: "వ్యాధి",
    severity: "తీవ్రత",
    date: "తేదీ",
    confidence: "నమ్మకం",
    aquaHealthPrediction: "ఆక్వా హెల్త్ అంచనా",
    scanFishShrimp: "చేప / రొయ్య స్కాన్",
    openCamera: "కెమెరా తెరవండి",
    chooseFromGallery: "గ్యాలరీ నుండి ఎంచుకోండి",
    selectedImage: "ఎంచుకున్న చిత్రం",
    analyzingImage: "చిత్రాన్ని విశ్లేషిస్తున్నారు…",
    testNow: "ఇప్పుడే పరీక్షించండి",
    scanImageError: "చిత్రాన్ని స్కాన్ చేయడంలో లోపం. దయచేసి మళ్లీ ప్రయత్నించండి.",
    detectionResult: "గుర్తింపు ఫలితం",
    type: "రకం",
    diseaseDetected: "గుర్తించిన వ్యాధి",
    confidenceScore: "నమ్మకం స్కోర్",
    advisoryInformation: "సలహా సమాచారం",
    symptoms: "లక్షణాలు",
    causes: "కారణాలు",
    treatment: "చికిత్స",
    prevention: "నివారణ",
    save: "సేవ్",
    testFurther: "ఇంకా పరీక్షించండి",
    reportSaved: "రిపోర్ట్ చరిత్రలో సేవ్ అయింది!",
    diseaseDetails: "వ్యాధి వివరాలు",
    searchDiseasesSymptoms: "వ్యాధులు లేదా లక్షణాలు వెతకండి...",
    fish: "చేప",
    shrimp: "రొయ్య",
    symptomsLabel: "లక్షణాలు",
    cause: "కారణం",
    noDiseasesFound: "మీ శోధనకు సరిపోయే వ్యాధులు కనబడలేదు.",
    symptomsToRecognize: "గుర్తించాల్సిన లక్షణాలు",
    pageNotFound: "అయ్యో! పేజీ కనిపించలేదు",
    returnHome: "హోమ్‌కి తిరిగి వెళ్లండి",
  },
};

export const t = (language: AppLanguage, key: string): string => {
  const table = translations[language] || translations.english;
  return table[key] || translations.english[key] || key;
};

export const translateSeverity = (language: AppLanguage, severity: string) => {
  const normalized = severity.toLowerCase();
  if (normalized === "high") return t(language, "high");
  if (normalized === "moderate" || normalized === "medium") return t(language, "moderate");
  if (normalized === "low") return t(language, "low");
  if (normalized === "uncertain") return t(language, "uncertain");
  return severity;
};

export const translateType = (language: AppLanguage, value: string) => {
  const normalized = value.toLowerCase();
  if (normalized === "fish") return t(language, "fish");
  if (normalized === "shrimp") return t(language, "shrimp");
  return value;
};
